{% set name = "alsa-plugins" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.alsa-project.org/pub/plugins/{{ name }}-{{ version }}.tar.bz2
  sha256: 1c0f06450c928d711719686c9dbece2d480184f36fab11b8f0534cb7b41e337d

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - alsa-lib
    - ffmpeg
    - jack >=0.98
    - pulseaudio >=0.9.11
  run:
    - {{ pin_compatible('jack', max_pin='x.x.x') }}

test:
  commands:
    {% set mods = [
        "conf_pulse",
        "ctl_arcam_av",
        "ctl_oss",
        "ctl_pulse",
        "pcm_a52",
        "pcm_jack",
        "pcm_oss",
        "pcm_pulse",
        "pcm_upmix",
        "pcm_usb_stream",
        "pcm_vdownmix",
        "rate_lavrate",
        "rate_lavrate_fast",
        "rate_lavrate_faster",
        "rate_lavrate_high",
        "rate_lavrate_higher",
        "rate_speexrate",
        "rate_speexrate_best",
        "rate_speexrate_medium",
    ] %}
    {% for mod in mods %}
    - test -f $PREFIX/lib/alsa-lib/libasound_module_{{ mod }}$SHLIB_EXT
    {% endfor %}

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later AND GPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.GPL
  summary: 'The Advanced Linux Sound Architecture (ALSA) - plugins'
  description: |
    Plugins for the ALSA library, including play or capture via JACK or Pulse Audio and
    stream conversions.
  dev_url: https://github.com/alsa-project/alsa-plugins

extra:
  recipe-maintainers:
    - ryanvolz
